stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
    - src/data/split_data.py
    outs:
    - data/processed_data
  scale_data:
    cmd: python src/data/scale_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/scale_data.py
    outs:
    - data/scaled_data/X_test_scaled.csv
    - data/scaled_data/X_train_scaled.csv
    - models/scaler.joblib
  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled_data/X_train_scaled.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled_data/X_train_scaled.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/best_model.pkl
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/y_test.csv
    - data/scaled_data/X_test_scaled.csv
    - models/best_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
